stages:
  - test
  - deploy
  - accessilibity

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Verify/Accessibility.gitlab-ci.yml

a11y:
  variables:
      a11y_urls: "https://lav15.ventsdouest.dev"
  # artifacts:
  #   paths: [gl-accessibility.json]
  #   reports:
  #     codequality:
  #       - gl-accessibility.json

code_quality:
  stage: test
  allow_failure: true
  variables:
    REPORT_FORMAT: json
  artifacts:
    reports:
      codequality:
        - gl-code-quality-report.json

# accessilibity: 
#   stage: test
#   image: node:21-alpine

deploy:
  stage: deploy
  image: alpine:latest
  variables:
    USER: root
    HOST: lav15.ventsdouest.dev
  before_script:
    - apk add --no-cache sshpass openssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | sshpass -Ppassphrase -f <(printf '%s\n' chantepie) ssh-add -
  script:
    - echo "Pulling repository..."
    - ssh -o StrictHostKeyChecking=accept-new $USER@$HOST "cd /docker/sae/data/web && git pull"
    - echo "Pulled"
  only:
    refs:
      - main