stages:
  - test
  - deploy

w3c-html-test:
  stage: test
  image: docker:26.1.2-dind-alpine3.19
  script:
    - echo "testing..."

deploy:
  stage: deploy
  image: docker:26.1.2-dind-alpine3.19
  script:
    - echo "waiting..."
  #when: manual
  #only:
  #  refs:
  #    - main