stages:
  #- test
  - deploy

# w3c-html-test:
#   stage: test
#   image: docker:26.1.2-dind-alpine3.19
#   script:
#     - echo "testing..."

deploy:
  stage: deploy
  image: alpine:latest
  variables:
    USER: root
    HOST: lav15.ventsdouest.dev
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh)' 
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - echo "Pulling repository..."
    - ssh $USER@$HOST "cd /docker/sae/data/web && git pull"
    - echo "Pulled"
  #when: manual
  #only:
  #  refs:
  #    - main