stages:
  - test
  - deploy
  - web-accessilibity

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - template: Verify/Accessibility.gitlab-ci.yml

a11y:
  stage: web-accessilibity
  variables:
      a11y_urls: "https://lav15.ventsdouest.dev"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

# code_quality:
#   variables:
#     REPORT_FORMAT: html
#   artifacts:
#     paths: [gl-code-quality-report.html]
#   rules:
#     - if: '$CI_COMMIT_REF_NAME == "develop" || $CI_COMMIT_REF_NAME =~ /feature\/.*/'
#   parallel: 2

deploy:
  stage: deploy
  image: alpine:latest
  variables:
    USER: root
    HOST: lav15.ventsdouest.dev
  before_script:
    - apk add --no-cache sshpass openssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | sshpass -Ppassphrase -f <(printf '%s\n' chantepie) ssh-add -
  script:
    - echo "Pulling repository..."
    - ssh -o StrictHostKeyChecking=accept-new $USER@$HOST "cd /docker/sae/data/web && git pull"
    - echo "Pulled"
  only:
    refs:
      - main