stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  variables:
    USER: root
    HOST: lav15.ventsdouest.dev
  before_script:
    - apk add --no-cache sshpass openssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | sshpass -Ppassphrase -f <(printf '%s\n' chantepie) ssh-add -
  script:
    - echo "Pulling repository..."
    - ssh -o StrictHostKeyChecking=accept-new $USER@$HOST "cd /docker/sae/data/web && git pull"
    - echo "Pulled"
  only:
    refs:
      - main