version: "3"
name: ${IMAGE_NAME}
services:
  apache:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    image: bigpapoo/r408-php:8.2-apache
    ports:
      - 8080:80
    volumes:
      - ../src:/var/www/html
    environment:
      - DB_HOST=postgres:3306
      - DB_DATABASE=alhaizbreizh
      - DB_USER=root
      - DB_PASSWORD=chantepie
  postgres:
    image: postgres:15.7-alpine3.19
    environment:
      - POSTGRES_PASSWORD=chantepie # useless to put a strong password there
      - POSTGRES_DB=alhaizbreizh
      - POSTGRES_USER=root
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: